spring:
  jpa:
    hibernate:
      ddl-auto: create
    h2:
      console:
        enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: testdb
    password: psw1234
    driverClassName: org.h2.Driver